### PR TITLE
Issue/17 trashcan

### PR DESCRIPTION
**Pull request by edoardocavazza**
- update SDK (new upload methods and new TrashCollection)
- refactor of list and form views (add editable mode and others)
- implement the TrashCollection and the `trashcan` routes, as well as the ability to restore and definitely delete an object

### CODE REVIEW

**Comment by stefanorosanelli** [comment]
Did some tests, seems ok but:
DELETE from trashcan is not working since a wrong API call is performed, e.g. ```DELETE /documents/123`` instead of ```DELETE /trash/123``` 

(see https://docs.bedita.net/en/latest/endpoints/trash.html#delete-contents)

**Comment by stefanorosanelli** [comment]
Some filter like search and type selection would be useful, like in `Data / Objects`

We can do it in a later issue if problematic.

**Comment by edoardocavazza** [comment]
It seems that filters for `/trashcan` API are not working, so I have disabled the filters form

**Comment by stefanorosanelli** [comment]
You're right, I'm opening an issue for that!

**Comment by stefanorosanelli** [comment]
Filters view for `Trashcan` will be implements after bedita/bedita#1308

**Pull request merged**
