### PR TITLE
Issue/25 relationship dialog

### PR DESCRIPTION
**Pull request by edoardocavazza**
Added some improvements to the relationships dialog:

- search and filter box
- dialog title
- related objects count

[`npm install` to update new dependencies]

### CODE REVIEW

**Comment by stefanorosanelli** [comment]
Seems ok - in a future version we will need a fixed list of available types for the given relation: you can filter from these types but not look for other types

Number of related items should be displayed also near the `ADD` button where the current list of related objects is displayed.

Also a pagination to browse currently related objects, if many, but we can do it later

**Comment by edoardocavazza** [comment]
> in a future version we will need a fixed list of available types for the given relation: you can filter from these types but not look for other types

Models are ready to do this, once `/object_types` endpoint is completed.

**Comment by edoardocavazza** [comment]
After 7bba3b3 , the relationships list shows the pagination bar (if pagination data are present). Otherwise, it just shows the number of related objects

**Comment by stefanorosanelli** [comment]
Godd job! Just a couple of problems:
 * changing page size on the toolbar near *ADD* causes redirecting to main objects page like `/?page=1&pageSize=10`
 * objects to add dialog: type removal via checkbox click does not remove the flag even if the filter seems to be correctly applied

**Comment by edoardocavazza** [comment]
fixed!

**Pull request merged**
