### PR TITLE
Issue/22 filter box

### PR DESCRIPTION
**Pull request by edoardocavazza**
This implements feature requested in #22:

- use `/objects?filter[types][ne]=users` endpoint
- when all filters are selected, the click on a checkbox filters for the single type

### CODE REVIEW

**Comment by stefanorosanelli** [comment]
* there's an error in `Streams` a wrong API call is performed: `/streams?filter[types][ne]=users` 
 * in relation objects search modal checkboxes are not working, or working in a weird way ;)

Type selection is fine, but probably need a simple way to just show all types without clicking all types. 
Another problematic behavior is: having all types selected there is no way to deselect a single type

**Comment by edoardocavazza** [comment]
All errors should be fixed now

**Comment by stefanorosanelli** [comment]
Everything seems ok!

Showed the new filter to @batopa we suggest these modifications:
 * when `all` checkbox is selected, unchecking `all` should remove all types selection and present an empty set, then it's probably more clear that a type selection must be done - a string like `No types selected` could be displayed to make ti even more clear
 * [minor] `all` checkbox should probably be put in a different position? not to be confused as one of the available types

**Comment by didoda** [comment]
`all` and 'none` are now a radio button.
When `all` is selected, then all checkboxes are selected too.
When `none` is selected, then all checkboxes (and `all` radio) are not selected and filter is not applied... filter is applied when at least one checkbox is active.

**Pull request merged**
